org: nubystech
service: duckDbAutomationV3

provider:
  name: aws
  runtime: python3.12
  architecture: arm64
  region: ap-south-1
  ecr:
    images:
      duckDbAutomationLambda:
        path: ./ # Path to folder containing Dockerfile

functions:
  handler:
    image:
      name: duckDbAutomationLambda
