name: Deploy Lambda

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - run: npm install -g serverless

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # Option 1: Login (requires Serverless Dashboard access token)
    #- run: serverless login --token ${{ secrets.SERVERLESS_ACCESS_TOKEN }}

    # Deploy disabling dashboard (Option 2)
    - run: sls deploy --org null --app null
